[WidgetShadow]
Meter=Shape
Shape=Rectangle (0*#ScaleDpi#),(0*#ScaleDpi#),(#LG.W#*#ScaleDpi#),(#LG.H#*#ScaleDpi#),(#LG.R#*#ScaleDpi#) | Fill Color 0,0,0,10 | StrokeWidth 0
Shape2=Rectangle (1*#ScaleDpi#),(2*#ScaleDpi#),(#LG.W#*#ScaleDpi#),(#LG.H#*#ScaleDpi#),(#LG.R#*#ScaleDpi#) | Fill Color 0,0,0,8 | StrokeWidth 0
Shape3=Rectangle (2*#ScaleDpi#),(4*#ScaleDpi#),(#LG.W#*#ScaleDpi#),(#LG.H#*#ScaleDpi#),(#LG.R#*#ScaleDpi#) | Fill Color 0,0,0,6 | StrokeWidth 0
Shape4=Rectangle (3*#ScaleDpi#),(6*#ScaleDpi#),(#LG.W#*#ScaleDpi#),(#LG.H#*#ScaleDpi#),(#LG.R#*#ScaleDpi#) | Fill Color 0,0,0,4 | StrokeWidth 0
Shape5=Rectangle (4*#ScaleDpi#),(8*#ScaleDpi#),(#LG.W#*#ScaleDpi#),(#LG.H#*#ScaleDpi#),(#LG.R#*#ScaleDpi#) | Fill Color 0,0,0,3 | StrokeWidth 0
Shape6=Rectangle (5*#ScaleDpi#),(11*#ScaleDpi#),(#LG.W#*#ScaleDpi#),(#LG.H#*#ScaleDpi#),(#LG.R#*#ScaleDpi#) | Fill Color 0,0,0,2 | StrokeWidth 0
Shape7=Rectangle (6*#ScaleDpi#),(14*#ScaleDpi#),(#LG.W#*#ScaleDpi#),(#LG.H#*#ScaleDpi#),(#LG.R#*#ScaleDpi#) | Fill Color 0,0,0,1 | StrokeWidth 0
AntiAlias=1
DynamicVariables=1
