[Variables]
CalSize=#CalSize#

Blur.OffsetX=0
Blur.OffsetY=0

Cal.Color.Month=255,56,60,255
Cal.Color.Today=255,56,60,255
Cal.Color.DayNames=36,36,36,255
Cal.Color.Weekend=36,36,36,160
Cal.Color.Dates=36,36,36,255
Cal.Color.WeekendDates=36,36,36,160
Cal.Color.TodayText=255,255,255,255
Clr.Hrl=242,242,247,200

CalDark.Color.Month=255,56,60,255
CalDark.Color.Today=255,56,60,255
CalDark.Color.DayNames=242,242,247,200
CalDark.Color.Weekend=242,242,247,120
CalDark.Color.Dates=242,242,247,200
CalDark.Color.WeekendDates=242,242,247,120
CalDark.Color.TodayText=242,242,247,200
CalDark.Color.Overlay=0,0,0,150
CalDark.Color.Border=255,255,255,30

DateEvents.Color.Month=255,56,60,255
DateEvents.Color.Today=255,56,60,255
DateEvents.Color.DayNames=36,36,36,255
DateEvents.Color.Weekend=36,36,36,160
DateEvents.Color.Dates=36,36,36,255
DateEvents.Color.WeekendDates=36,36,36,160
DateEvents.Color.TodayText=255,255,255,255
DateEvents.Color.Overlay=255,255,255,140
DateEvents.Color.Border=255,255,255,60
DateEvents.Color.DayName=255,56,60,255
DateEvents.Color.DayNumber=36,36,36,255

DateEventsDark.Color.Month=255,56,60,255
DateEventsDark.Color.Today=255,56,60,255
DateEventsDark.Color.DayNames=242,242,247,200
DateEventsDark.Color.Weekend=242,242,247,120
DateEventsDark.Color.Dates=242,242,247,200
DateEventsDark.Color.WeekendDates=242,242,247,120
DateEventsDark.Color.TodayText=242,242,247,200
DateEventsDark.Color.Overlay=0,0,0,150
DateEventsDark.Color.Border=255,255,255,30
DateEventsDark.Color.DayName=255,66,69,255
DateEventsDark.Color.DayNumber=255,255,255,255

Cal.FontFace=Inter
Cal.FontWeight=600

Date.FontFace=Inter
Date.FontWeight=500

CalWide.Events.FontWeight=400

DateEvents.FontFace=Inter
DateEvents.FontWeight=600

DateEvents.Events.FontWeight=400

DateEventsDark.FontFace=Inter
DateEventsDark.FontWeight=600

DateEventsDark.Events.FontWeight=400

C.w=(#CalSize#*7/55)
C.h=(#CalSize#*7/55+#CalSize#*6/500)
Space.x=(#CalSize#*4/500)
Space.y=(#CalSize#*4/500)
Bumper.x=(#CalSize#/11)
Bumper.left=(#CalSize#/11)
Bumper.right=(#CalSize#/11)
Bumper.top=(#CalSize#/11)
Bumper.bottom=(#CalSize#/11)
Cal.FontSize=(#CalSize#*13/220)
DateEvents.FontSize=(#CalSize#*13/220)
DateEventsDark.FontSize=(#CalSize#*13/220)

Date.Blur.OffsetX=0
Date.Blur.OffsetY=0
Date.Color.DayName=255,56,60,255
Date.Color.DayNumber=36,36,36,255
Date.Color.Border=255,255,255,60
Date.Color.Overlay=255,255,255,140

DateEvents.Blur.OffsetX=0
DateEvents.Blur.OffsetY=0

DateDark.IconSize=#Date.IconSize#
DateDark.Blur.OffsetX=0
DateDark.Blur.OffsetY=0
DateDark.Color.DayName=255,66,69,255
DateDark.Color.DayNumber=255,255,255,255
DateDark.Color.Border=255,255,255,30
DateDark.Color.Overlay=0,0,0,150

DateEventsDark.IconSize=#DateEvents.IconSize#
DateEventsDark.Blur.OffsetX=0
DateEventsDark.Blur.OffsetY=0

ManualNote=
ManualNote2=
ManualNote3=
ManualNote4=
ManualNote5=


