[Variables]

Wea.W=#WeatherSize#
Wea.H=#Wea.W#
Wea.Radius=(#Wea.W#*0.08)

Wea.FontFace=SF Pro Display

Wea.FontWeight.City=500
Wea.FontWeight.Temp=400
Wea.FontWeight.Condition=500
Wea.FontWeight.HiLo=500

Wea.FontSize.City=(#Wea.W#*0.07)
Wea.FontSize.Temp=(#Wea.W#*0.20)
Wea.FontSize.Condition=(#Wea.W#*0.06)
Wea.FontSize.HiLo=(#Wea.W#*0.06)

Wea.Pad=(#Wea.W#*0.11)
Wea.Y.City=(#Wea.H#*0.08)
Wea.Y.Temp=(#Wea.H#*0.17)
Wea.Y.Icon=(#Wea.H#*0.54)
Wea.IconSize=(#Wea.H#*0.15)
Wea.Y.Summary=(#Wea.H#*0.71)
Wea.Y.HiLo=(#Wea.H#*0.81)

Wea.Color.Text=255,255,255,255
Wea.Color.HiLo=255,255,255,255

Wea.Lat=7.290572
Wea.Lon=80.633728
Wea.City=Kandy

; Weather update interval (in Rainmeter update cycles)
Wea.UpdateRate=120

; Location update interval (in Rainmeter update cycles)
Wea.LocationUpdateRate=720

Wea.Blur.OffsetX=0
Wea.Blur.OffsetY=0
